from typing import List, Optional, Literal
from pydantic import BaseModel, Field

""" schemas for each agent """


class SystemDesignOutput(BaseModel):
    """Structured output generated by the System Designer agent."""
    architecture_summary: str = Field(
        ..., description="High-level summary of the proposed system architecture."
    )
    component_breakdown: List[str] = Field(
        ..., description="List of key system components and their responsibilities."
    )
    data_models: List[str] = Field(
        ..., description="Key database schemas, entities, or JSON payloads required."
    )
    api_contracts: List[str] = Field(
        ..., description="List of API endpoints (REST/GraphQL/gRPC) and expected signatures."
    )
    design_spec_markdown: str = Field(
        ..., description="Full technical design specification formatted in Markdown."
    )


class BackendEngineerOutput(BaseModel):
    """Structured output generated by the Backend Engineer agent."""
    implemented_files: List[str] = Field(
        ..., description="List of file paths generated or modified (e.g., backend.py, models.py)."
    )
    endpoints_created: List[str] = Field(
        ..., description="API endpoints created during implementation."
    )
    database_setup: str = Field(
        ..., description="Summary of database migrations, models, or storage implementations."
    )
    execution_status: Literal["success", "failed", "partial"] = Field(
        ..., description="Status of the backend task execution."
    )
    deliverables_summary: str = Field(
        ..., description="Detailed markdown overview of the backend deliverables."
    )


class FrontendEngineerOutput(BaseModel):
    """Structured output generated by the Frontend Engineer agent."""
    implemented_files: List[str] = Field(
        ..., description="List of file paths generated or modified (e.g., index.html, App.jsx)."
    )
    ui_components: List[str] = Field(
        ..., description="Key UI components or pages created."
    )
    backend_integration_notes: str = Field(
        ..., description="Details on how backend APIs were bound to the UI elements."
    )
    execution_status: Literal["success", "failed", "partial"] = Field(
        ..., description="Status of the frontend task execution."
    )
    deliverables_summary: str = Field(
        ..., description="Detailed markdown overview of the frontend deliverables."
    )


class QualityAssuranceOutput(BaseModel):
    """Structured output generated by the QA Engineer agent."""
    test_cases_evaluated: List[str] = Field(
        ..., description="List of verification scenarios or test suites run."
    )
    passed_checks: List[str] = Field(
        ..., description="List of requirements or endpoints verified successfully."
    )
    identified_issues: List[str] = Field(
        default_factory=list,
        description="Bugs, missing requirements, or edge-case failures found."
    )
    is_ready_for_deployment: bool = Field(
        ..., description="True if the project meets all functional criteria without blocking errors."
    )
    qa_report_markdown: str = Field(
        ..., description="Comprehensive QA summary report formatted in Markdown."
    )


class OrchestratorStepResult(BaseModel):
    """Represents the execution result of an individual step managed by the Orchestrator."""
    step_id: int = Field(..., description="Step ID tracked on the SQLite board.")
    agent_role: Literal["designer", "backend", "frontend", "qa"] = Field(
        ..., description="The role assigned to handle this step."
    )
    task_objective: str = Field(..., description="Objective assigned to the agent.")
    status: Literal["completed", "failed"] = Field(
        ..., description="Completion state of the step."
    )
    output_summary: str = Field(..., description="Short summary of the step execution result.")


class OrchestratorOutput(BaseModel):
    """Final structured output returned by the Orchestrator agent for a project goal."""
    project_goal: str = Field(..., description="Original goal provided to the team.")
    final_status: Literal["success", "failed", "partially_completed"] = Field(
        ..., description="Overall completion status of the project goal."
    )
    execution_steps: List[OrchestratorStepResult] = Field(
        default_factory=list,
        description="Sequential step breakdown executed across the agent team."
    )
    deployed_server_url: Optional[str] = Field(
        default=None,
        description="Local web server URL if launched during execution (e.g., http://localhost:8000)."
    )
    executive_summary: str = Field(
        ..., description="Final markdown overview summarizing the completed project deliverables."
    )